### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by alexkavon** [whiteout-io/imap-handler#10]
My app is crashing every time the handler meets an unexpected character. Is there something I'm missing about handling errors? Here's the error stack:
~~~
/home/alex/poste/node_modules/wo-imap-handler/src/imap-parser.js:86
                throw new Error("Unexpected char at position " + (this.pos + e
                      ^
Error: Unexpected char at position 4
    at ParserInstance.getElement (/home/alex/poste/node_modules/wo-imap-handler/src/imap-parser.js:86:23)
    at ParserInstance.getTag (/home/alex/poste/node_modules/wo-imap-handler/src/imap-parser.js:44:29)
    at Object.parser (/home/alex/poste/node_modules/wo-imap-handler/src/imap-parser.js:590:31)
    at parse (/home/alex/poste/lib/commands.js:11:18)
    at Object.exports.process (/home/alex/poste/lib/commands.js:21:2)
    at CleartextStream.<anonymous> (/home/alex/poste/lib/imap.js:23:14)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
~~~

**Comment by alexkavon** [comment]
Never mind, I just made some regexp to scrape out control characters instead.

**Comment by asutherland** [comment]
Can you elaborate on what control characters you have to scrape out?

My understanding is that imap-handler is pretty strict because it evolved out of the hoodiecrow test IMAP server where it is beneficial to complain a lot about syntax errors.  Things have been relaxed somewhat and the grammar made to deal with more realistic situations, but it's possible there's a need to explicitly handle certain cases better, and to make things less explodey in general.

So if you're seeing a pattern from an IMAP server that breaks things, it'd be great to know what it is so it can be fixed rather than you having to regexp sanitize everything you feed imap-handler.

**Comment by alexkavon** [comment]
Here's my regex code.

~~~
\x00-\x1F\x7F
~~~

One other off topic thing I've noticed is that if you only supply a tag it will error out.
